name: stub runs
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - run: nextflow run ${GITHUB_WORKSPACE} -stub -profile wgs --csv ${GITHUB_WORKSPACE}/tests/data/stub-run-wgs-single.csv
